# Generated by Django 5.1.3 on 2024-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song_title', models.CharField(max_length=100)),
                ('released_as', models.CharField(max_length=50)),
                ('part_of', models.CharField(max_length=50)),
                ('partof_format', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('artist_name', models.CharField(max_length=50)),
            ],
        ),
    ]
