# Generated by Django 5.1.3 on 2024-12-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='part_of',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='partof_format',
            new_name='album_format',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='released_as',
            new_name='release_type',
        ),
    ]
